### ISSUE TITLE
How to run modpo?

### ISSUE THREAD

**Issue by CurryxIaoHu** [ZHZisZZ/modpo#1]
Thanks for the authors' great work! However, I find it difficult to reproduce the results. Can authors give some tutorials to run this code? For example, how can I get "margin_reward_model_name"?

**Comment by ZHZisZZ** [comment]
Hi, you can go through the [tutorial for safety alignment](https://github.com/ZHZisZZ/modpo/blob/main/scripts/modpo/beavertails/README.md). If you have any questions afterward, feel free to ask。

**Comment by CurryxIaoHu** [comment]
Thank you. I just missed it. Does the experiment 'Summarization with length penalty' belong to any part in the paper? I find the paper mainly contains two experiments, which are safety alignment and Long-form QA.
