### ISSUE TITLE
How to run multi-objective(>=3) dpo?

### ISSUE THREAD

**Issue by CurryxIaoHu** [ZHZisZZ/modpo#2]
How can I run the script to train a model that is helpful, honest, harmless? For example, should I train two reward models on helpful and honest datasets respectively using DPO and finally apply MODPO on a harmless dataset?

**Comment by ZHZisZZ** [comment]
1. Train a helpful reward model and a honest reward model (e.g., with DPO and LoRA, here is an [example command](https://github.com/ZHZisZZ/modpo/blob/main/scripts/modpo/beavertails/run.sh#L17-L32)) 
2. Train a language model on a harmless dataset with these two reward models as margin; 
You need to make these changes to the [modpo.py](https://github.com/ZHZisZZ/modpo/blob/main/scripts/modpo/beavertails/modpo.py) to support training w/ >=3 objectives:
    a. Load loRA weights for two reward models; https://github.com/ZHZisZZ/modpo/blob/main/scripts/modpo/beavertails/modpo.py#L102
    ```python
    model.load_adapter(script_args.helpful_reward_model_name, adapter_name="helpful_reward")
    model.load_adapter(script_args.honest_reward_model_name, adapter_name="honest_reward")
    ```
    b. Add these two reward models to trainers; https://github.com/ZHZisZZ/modpo/blob/main/scripts/modpo/beavertails/modpo.py#L135-L147
    ```python
      trainer.set_wrapped_margin_reward_model_list(
          RewardWrapperList([
              ImplicitRewardWrapper(
                  model=PeftAsPreTrained(trainer.model, "helpful_reward"),
                  ref_model=PeftAsPreTrained(trainer.model), 
                  tokenizer=tokenizer, 
                  beta=script_args.beta,
                  prompt_template=script_args.prompt_template,
              ),
              ImplicitRewardWrapper(
                  model=PeftAsPreTrained(trainer.model, "honest_reward"),
                  ref_model=PeftAsPreTrained(trainer.model), 
                  tokenizer=tokenizer, 
                  beta=script_args.beta,
                  prompt_template=script_args.prompt_template,
              ),
          ]), 
          w=(1/3, 1/3, 1/3), # example weights
          prepare=False,
      )
    ```
